# Statistical Functions in Numpy

In [35]:
import numpy as np

In [36]:
arr = np.array([[0,1],[2, 3]])
arr

array([[0, 1],
       [2, 3]])

In [37]:
# Maximin number in an array
arr.max()

3

In [38]:
# Minimum Number in Array
arr.min()

0

In [39]:
# Maximum values along second axis
np.amax(arr,1)

array([1, 3])

In [40]:
# Minimum values along second axis
np.amin(arr,1)

array([0, 2])

In [41]:
# 80 percentile of array
arr = np.array([1.0, 2.0, 3.0, 4.0])
np.percentile(arr,80)

3.4000000000000004

In [42]:
# Median of Array
arr = np.array([[0,1,2,3,4,5],[6,7,8,9,10,11]])
np.median(arr)

5.5

In [43]:
# Mean oof Array
np.mean(arr)

5.5

In [44]:
# standard deviation
np.std(arr)

3.452052529534663

In [45]:
# Variance 
np.var(arr)

11.916666666666666

In [46]:
# Convariance of Two Arrays
arr1 = np.array([33,56,78])
arr2 = np.array([23,61,20])
np.cov(arr1,arr2)

array([[506.33333333, -27.16666667],
       [-27.16666667, 522.33333333]])

In [47]:
# Cross-Correlation of Two Arrays
arr1 = np.array([7,9,14])
arr2 = np.array([9,3,27])
np.correlate(arr1,arr2)

array([468])

# Linear algebraic fuctions in Numpy

In [48]:
# Dot Product of two matrices(2D Array)
p = np.array([[1, 0], [0, 1]])
q = np.array([[1, 2], [3, 4]])

np.dot(p,q)

array([[1, 2],
       [3, 4]])

In [49]:
# Outer Product of two matrices(2D Array)
p = np.array([[1, 0], [0, 1]])
q = np.array([[1, 2], [3, 4]])

np.outer(p,q)

array([[1, 2, 3, 4],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [1, 2, 3, 4]])

In [50]:
# Cross Product of Two matrices
p = np.array([[1, 0], [0, 1]])
q = np.array([[1, 2], [3, 4]])

print(np.cross(p,q))

print(np.cross(q,p))

[ 2 -3]
[-2  3]


In [51]:
# Determinant of Array
arr = np.arange(16).reshape(4,4)
np.linalg.det(arr)

-2.9582283945787796e-30

In [52]:
# Inverse of a matrix
arr = np.array([[1,2],[3,4]])
inverse = np.linalg.inv(arr)
inverse

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [53]:
# Rank of a Matrix
arr = np.array([[1,2],[3,4]])
np.linalg.matrix_rank(arr)

2