# Numpy Introduction

In [114]:
import numpy as np

Comparing Time Complexity of np.array with list

In [115]:
my_array = np.arange(1000000)

In [116]:
my_list = list(range(1000000))

In [117]:
# Calculation time for operation on np.array
%time for _ in range(10): arr2 = my_array * 2

CPU times: total: 31.2 ms
Wall time: 23.9 ms


In [118]:
# Calculating time for operations on list
%time for _ in range(10): list2 = my_list * 2

CPU times: total: 328 ms
Wall time: 343 ms


So, Array is faster than list on large data

1D Array

In [119]:
import numpy as np
arr1D = np.arange(2,10)
arr1

array([2, 3, 4, 5, 6, 7, 8, 9])

2d Array

In [120]:
import numpy as np
arr2D = np.arange(2,10).reshape(2,4)
arr2D

array([[2, 3, 4, 5],
       [6, 7, 8, 9]])

3D Array

In [121]:
import numpy as np
arr3D = np.arange(2,20).reshape(3,3,2)
arr3D

array([[[ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13]],

       [[14, 15],
        [16, 17],
        [18, 19]]])

In [122]:
import numpy as np

In [123]:
# Reverse any array
ar1 = np.array(range(2,20))
print("Original Array")
print(ar1)
print("After Reversing")
ar2 = ar1[::-1]
ar2

Original Array
[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
After Reversing


array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,
        2])

In [124]:
# creating a 2d array with 1 on the border and 0 inside
ar3 = np.ones((5,5))
print(ar3)
ar3[1:-1,1:-1] = 0
ar3

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [125]:
# Creating an 2D array
ar4 = np.arange(16).reshape(4,4)
ar4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [126]:
# Accessing elements of array by indexes and updating them

In [127]:
ar4[1,1] =0

In [128]:
ar4[1,2]=0

In [129]:
ar4[2,1]=0

In [130]:
ar4[2,2]=0

In [131]:
ar4

array([[ 0,  1,  2,  3],
       [ 4,  0,  0,  7],
       [ 8,  0,  0, 11],
       [12, 13, 14, 15]])

In [132]:
# Creating 8x8 array
ar5 = np.arange(64).reshape(8,8)
print("Before Updating")
print(ar5)
# Updating Selected values of array
for i in range(8):
    for j in range(8):
        if (i+j)%2 == 0:
            ar5[i,j] = 0
        else:
            ar5[i,j] = 1
print("After updating")
ar5

Before Updating
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]
 [32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47]
 [48 49 50 51 52 53 54 55]
 [56 57 58 59 60 61 62 63]]
After updating


array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [133]:
# list and tuple into array
my_list = [2,3,4,5,6,7]
print("list to arary:")
print(np.asarray(my_list))
my_tuple=([8,4,6],[1,2,3])
print("Tuple to array:")
print(np.asarray(my_tuple))

list to arary:
[2 3 4 5 6 7]
Tuple to array:
[[8 4 6]
 [1 2 3]]


In [134]:
arr6 = [10,20,30]
arr6 = np.append(arr6,[[40,50,60],[70,80,90]])
arr6

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

Arithmetic Operation with numpy Arrays

In [135]:
arr = np.array([[1.,2.,3.],[4.,5.,6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [136]:
# Array Multiplication
arr*arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [137]:
# Array Difference
arr-arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [138]:
# Array Division
arr/arr

array([[1., 1., 1.],
       [1., 1., 1.]])

In [139]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [140]:
# Compute eponential value of items in Array
arr**3

array([[  1.,   8.,  27.],
       [ 64., 125., 216.]])

In [141]:
arr2 = np.array([[0.,4.,1.],[7.,2.,12.]])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [142]:
# Comparing Two Arrays
arr2>arr

array([[False,  True, False],
       [ True, False,  True]])

In [143]:
x = np.array([-4, -3, -2, -1, 0, 1, 2, 3, 4])
r1 = np.signbit(x)
r1

array([ True,  True,  True,  True, False, False, False, False, False])

In [144]:
x = np.array([1, np.e, np.e**2])
x
print("Natural Log:")
print(np.log(x))
print("Common Log:")
print(np.log10(x))
print("Base 2 log:")
print(np.log2(x))

Natural Log:
[0. 1. 2.]
Common Log:
[0.         0.43429448 0.86858896]
Base 2 log:
[0.         1.44269504 2.88539008]


In [145]:
arr = np.array([ 3.1, 3.5, 4.5, 2.9, -3.1, -3.5, -5.9])
print("around function:")
print(np.around(arr))
print("floor function:")
print(np.floor(arr))
print("ceil function:")
print(np.ceil(arr))
print("truncated function:")
print(np.trunc(arr))
print("Round function:")
print([round(elem) for elem in x])

around function:
[ 3.  4.  4.  3. -3. -4. -6.]
floor function:
[ 3.  3.  4.  2. -4. -4. -6.]
ceil function:
[ 4.  4.  5.  3. -3. -3. -5.]
truncated function:
[ 3.  3.  4.  2. -3. -3. -5.]
Round function:
[1, 3, 7]


In [146]:
arr = np.array([0., 30., 45., 60., 90.])
print("Sine:")
print(np.sin(arr))
print("Cosine:")
print(np.cos(arr))
print("Tangent:")
print(np.tan(arr))

Sine:
[ 0.         -0.98803162  0.85090352 -0.30481062  0.89399666]
Cosine:
[ 1.          0.15425145  0.52532199 -0.95241298 -0.44807362]
Tangent:
[ 0.         -6.4053312   1.61977519  0.32004039 -1.99520041]


In [147]:
arr = np.array([-1., 0, 1.])
print("Inverse Sine:")
print(np.arcsin(arr))
print("Inverse Cosine:")
print(np.arccos(arr))
print("Inverse Tangent:")
print("np.arctan(arr)")

Inverse Sine:
[-1.57079633  0.          1.57079633]
Inverse Cosine:
[3.14159265 1.57079633 0.        ]
Inverse Tangent:
np.arctan(arr)


Indexing and Slicing

In [148]:
x = np.array([
  [11 ,22, 33], 
  [44, 55, 66], 
  [77, 88, 99]])

In [149]:
# printing the third column of array
x[:,2]

array([33, 66, 99])

In [150]:
y = np.array([
  [3,6,9,12], 
  [15,18,21,24], 
  [27,30,33,36], 
  [39,42,45,48],
  [51,54,57,60]
  ])

In [151]:
# Returning odd rows and even coloumns
y[::2,1::2]

array([[ 6, 12],
       [30, 36],
       [54, 60]])