**Deep Learning**

** - Deep Learning is a subset of Machine Learning that is a subset of Artificial Intelligance - **

-Deep Learning is a branch of Machine Learning which focuses on using artificial neural networks with numerous layers to analyze input data and make predictions or decisions.


-Neural Networks are a category of machine learning models that are inspired by the way the brain works. They are composed of layers of connected "neurons" that process input data and make predictions based on that data.

**Building Blocks of Deep Learning**

- Weights: parameters of a neural network that are learned during training.

- Neurons: process input data and make predictions based on that data

- Layers: Interconnected nodes or "neurons".
                    There are several types of layers, including input,output, and hidden layers

- A loss function: How the network will be able to measure its performance on the training data, and thus how it will be able to steer itself in the right direc- tion.

- An optimizer: The mechanism through which the network will update itself based on the data it sees and its loss function. 

**Neural Network**

In [1]:
# Loading Training and Testing data 

from keras.datasets import mnist
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

11490434/11490434 [==============================] - 24s 2us/step


In [2]:
train_images.shape

(60000, 28, 28)

In [3]:
len(train_labels)

60000

In [4]:
train_labels

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [5]:
test_images.shape

(10000, 28, 28)

In [6]:
len(test_images)

10000

In [7]:
test_labels

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

In [8]:
# The network architecture

from keras import models
from keras import layers
network = models.Sequential()
network.add(layers.Dense(512, activation='relu', input_shape=(28 * 28,)))
network.add(layers.Dense(10, activation='softmax'))

In [9]:
# The compilation step

network.compile(optimizer='rmsprop',
        loss='categorical_crossentropy',
        metrics=['accuracy'])

In [11]:
# Preparing the image data

train_images = train_images.reshape((60000, 28 * 28))
train_images = train_images.astype('float32') / 255
test_images = test_images.reshape((10000, 28 * 28))
test_images = test_images.astype('float32') / 255

In [12]:
# Preparing the labels

from keras.utils import to_categorical
train_labels = to_categorical(train_labels)
test_labels = to_categorical(test_labels)

In [14]:
# fit the model

network.fit(train_images, train_labels, epochs=5, batch_size=128)

Epoch 1/5
469/469 [==============================] - 8s 9ms/step - loss: 0.2666 - accuracy: 0.9225
Epoch 2/5
469/469 [==============================] - 4s 9ms/step - loss: 0.1086 - accuracy: 0.9674
Epoch 3/5
469/469 [==============================] - 4s 9ms/step - loss: 0.0715 - accuracy: 0.9782
Epoch 4/5
469/469 [==============================] - 4s 8ms/step - loss: 0.0515 - accuracy: 0.9846
Epoch 5/5
469/469 [==============================] - 4s 9ms/step - loss: 0.0388 - accuracy: 0.9881


In [15]:
# check model performance on test data

test_loss, test_acc = network.evaluate(test_images, test_labels)
print('test_acc:', test_acc)

313/313 [==============================] - 1s 2ms/step - loss: 0.0677 - accuracy: 0.9780
test_acc: 0.9779999852180481


**Tensors and Tensor Operations**

In [16]:
#  Scalars (0D tensors)

import numpy as np
x = np.array(12)
x

array(12)

In [18]:
x.ndim

1

In [19]:
#  Vectors (1D tensors)

x = np.array([12, 3, 6, 14])
x

array([12,  3,  6, 14])

In [20]:
x.ndim

1

In [23]:
# Matrices (2D tensors)

x = np.array([[5, 78, 2, 34, 0],
            [6, 79, 3, 35, 1],
            [7, 80, 4, 36, 2]])
x

array([[ 5, 78,  2, 34,  0],
       [ 6, 79,  3, 35,  1],
       [ 7, 80,  4, 36,  2]])

In [25]:
x.ndim

2

In [26]:
# 3D tensors and higher-dimensional tensors



In [27]:
 x = np.array([[[5, 78, 2, 34, 0],
    [6, 79, 3, 35, 1],
    [7, 80, 4, 36, 2]],
    [[5, 78, 2, 34, 0],
    [6, 79, 3, 35, 1],
    [7, 80, 4, 36, 2]],
    [[5, 78, 2, 34, 0],
    [6, 79, 3, 35, 1],
    [7, 80, 4, 36, 2]]])
x

array([[[ 5, 78,  2, 34,  0],
        [ 6, 79,  3, 35,  1],
        [ 7, 80,  4, 36,  2]],

       [[ 5, 78,  2, 34,  0],
        [ 6, 79,  3, 35,  1],
        [ 7, 80,  4, 36,  2]],

       [[ 5, 78,  2, 34,  0],
        [ 6, 79,  3, 35,  1],
        [ 7, 80,  4, 36,  2]]])

In [28]:
x.ndim

3

In [ ]:
"""Tensor Operations"""

In [30]:
# Element-wise Operations

z=x+x  # Element-wise Addition

z = np.maximum(z, 0.)  # Element-wise relu

In [31]:
# Broadcasting

import numpy as np
x = np.random.random((64, 3, 32, 10))
y = np.random.random((32, 10))
z = np.maximum(x, y)

In [36]:
#  Tensor dot

import numpy as np
x = np.random.random((10,5))
y = np.random.random((5, 6))
z = np.dot(x, y)

In [38]:
#  Tensor reshaping

x = np.array([[0., 1.],
    [2., 3.],
    [4., 5.]])
print(x)

x = x.reshape((6, 1))
x

[[0. 1.]
 [2. 3.]
 [4. 5.]]


array([[0.],
       [1.],
       [2.],
       [3.],
       [4.],
       [5.]])

In [42]:
x = x.reshape((2,3))
x

array([[0., 1., 2.],
       [3., 4., 5.]])