# Broadcasting in Numpy

In [72]:
# Broadcasting describes that how arithmetic works between Arrays of Different shapes..

In [73]:
import numpy as np

In [74]:
'''Combining Scalar value with array'''
arr = np.arange(5)
print(arr)
arr = arr*5
arr

[0 1 2 3 4]


array([ 0,  5, 10, 15, 20])

In [75]:
'''De-meaning the array'''

arr = np.random.randn(4,3)
print(arr)
print()
arr.mean(0)  # Mean along axis 0
demean = arr - arr.mean(0)
print(demean)
print()

print(demean.mean(0))

[[-0.83367328 -1.47605593 -0.70552126]
 [-1.50723949  0.39766357  0.20235573]
 [-0.15379618  0.70746138  1.41646114]
 [-1.30021772 -0.31893081  1.08862303]]

[[ 0.11505839 -1.30359049 -1.20600092]
 [-0.55850783  0.57012902 -0.29812393]
 [ 0.79493549  0.87992683  0.91598148]
 [-0.35148605 -0.14646536  0.58814337]]

[ 8.32667268e-17 -4.16333634e-17  5.55111512e-17]


Shape Compatibility Rules:

a) If x, y have a different number of dimensions, prepend 1's to the shape of the shorter.

b) Any axis of length 1 can be repeated (broadcast) to the length of the other vector's length in that axis

c) All other axes must have matching lengths.

'''Examples of Compatibility'''

In [ ]:

'''Example 1'''

x.shape == (2, 3)

y.shape == (2, 3)  # compatible
y.shape == (2, 1)  # compatible
y.shape == (1, 3)  # compatible
y.shape == (3,)  # compatible

# results in (2, 3) shape

y.shape == (3, 2)  # NOT compatible
y.shape == (2,)  # NOT compatible


In [ ]:

'''Example 2'''

x.shape == (1000, 256, 256, 256)

y.shape == (1000, 256, 256, 256)  # compatible
y.shape == (1000, 1, 256, 256)  # compatible
y.shape == (1000, 1, 1, 256)  # compatible
y.shape == (1, 256, 256, 256)  # compatible
y.shape == (1, 1, 256, 1)  # compatible

# results in (1000, 256, 256, 256) shape

y.shape == (1000, 256, 256)  # NOT compatible


In [ ]:

'''Example 3'''

x.shape == (1, 2, 3, 5, 1, 11, 1, 17)
y.shape ==          (1, 7, 1,  1, 17)  # compatible

# results in shape (1, 2, 3, 5, 7, 11, 1, 17)


Adding Arrays of Different Shapes

In [76]:
'''Example 1'''

v1 = np.arange(4).reshape(4,1)
print(v1)

v2 = np.arange(4).reshape(1,4)
print(v2)

v1+v2

[[0]
 [1]
 [2]
 [3]]
[[0 1 2 3]]


array([[0, 1, 2, 3],
       [1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6]])

In [77]:
'''Example 2'''

x = np.array([[0, 1, 2],
              [3, 4, 5],
              [6, 7, 8]])
y = np.array([1, 10, 100]).reshape(3, 1)

print(x + y)

[[  1   2   3]
 [ 13  14  15]
 [106 107 108]]


In [78]:
'''Example 3'''

x = np.array([[[0, 1, 2],
               [3, 4, 5],
               [6, 7, 8]],
              [[9, 10, 11],
               [12, 13, 14],
               [15, 16, 17]]])  # shape (2, 3, 3)
y = np.array([1, 10, 100])     # shape       (3,)

print(x + y)


[[[  1  11 102]
  [  4  14 105]
  [  7  17 108]]

 [[ 10  20 111]
  [ 13  23 114]
  [ 16  26 117]]]


In [79]:
'''Example 4'''

x = np.array([[0], [1], [2]])  # (3, 1)
y = np.array([[3, 4, 5]])     # (1, 3)

print(x + y)

[[3 4 5]
 [4 5 6]
 [5 6 7]]


''' Broadcasting over other axis '''

In [80]:
arr = np.arange(12).reshape(4,3)
print(arr)

# Not compatible for broadcasting
arr-arr.mean(1)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


ValueError: operands could not be broadcast together with shapes (4,3) (4,) 

In [81]:
# Reshaping for compatibility for Broadcasting
arr-arr.mean(1).reshape((4,1))

array([[-1.,  0.,  1.],
       [-1.,  0.,  1.],
       [-1.,  0.,  1.],
       [-1.,  0.,  1.]])

Adding new axis using (np.newaxis) for Broadcasting purpose

In [82]:
arr = np.zeros((4, 4))
arr_3d = arr[:, np.newaxis, :]
print(arr_3d.shape)

arr_1d = np.random.normal(size=3)
print(arr_1d[:,np.newaxis])


arr = arr_1d[np.newaxis, :]

arr[np.newaxis, :].shape


(4, 1, 4)
[[ 0.10273   ]
 [-0.46242588]
 [-1.89056641]]


(1, 1, 3)

In [83]:

'''Demeanig a 3-D Array'''

arr = np.random.rand(3,4,5)
depth_means = arr.mean(2)

print(depth_means)

print(depth_means.shape)

demeaned = arr = depth_means[:,:,np.newaxis]
demeaned.mean(2)

[[0.39859729 0.70980045 0.63172099 0.29588407]
 [0.73769204 0.26471627 0.59653321 0.36520167]
 [0.34172652 0.42075402 0.67339772 0.51421316]]
(3, 4)


array([[0.39859729, 0.70980045, 0.63172099, 0.29588407],
       [0.73769204, 0.26471627, 0.59653321, 0.36520167],
       [0.34172652, 0.42075402, 0.67339772, 0.51421316]])

'''Setting Array Values by Broadcasting''' 

In [84]:
arr = np.zeros((4,3))

arr[:] = 5

arr

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [85]:
col = np.array([1.28, -0.42, 0.44, 1.6])
arr[:] = col[:, np.newaxis]
arr

array([[ 1.28,  1.28,  1.28],
       [-0.42, -0.42, -0.42],
       [ 0.44,  0.44,  0.44],
       [ 1.6 ,  1.6 ,  1.6 ]])

In [86]:
arr[:2] = [[-1.33],[0.580]]
arr

array([[-1.33, -1.33, -1.33],
       [ 0.58,  0.58,  0.58],
       [ 0.44,  0.44,  0.44],
       [ 1.6 ,  1.6 ,  1.6 ]])